# Usa una imagen oficial de Node
FROM node:20

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del proyecto Nest al contenedor
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto por donde Nest servirá la app
EXPOSE 3000

# Comando por defecto para iniciar Nest
CMD ["npm", "run", "start:dev"]
